version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - app_network

  frontend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
